- .travis.yml
Updated Travis CI to fix CodeCov and building on iOS
> Updated Travis CI

- Sources/ATTConnection.swift
- Sources/ATTProtocolDataUnit.swift
- Sources/GATTClient.swift
- Tests/BluetoothTests/AttributeProtocolTests.swift
- Tests/BluetoothTests/BluetoothTests.swift
- Tests/BluetoothTests/L2CAPSocket.swift
- Xcode/Bluetooth.xcodeproj/project.pbxproj
- Xcode/Bluetooth.xcodeproj/xcshareddata/xcbaselines/6EE84DC01CAF5C7C00A40C4D.xcbaseline/E272A968-C86F-4169-956E-E6220948798B.plist
- Xcode/Bluetooth.xcodeproj/xcshareddata/xcbaselines/6EE84DC01CAF5C7C00A40C4D.xcbaseline/Info.plist
**Issue**
Fixes #14.
Adds a test L2CAP socket for TDD with GATT.
`BluetoothTests/TestL2CAPSocket.swift`
> #14 Added `TestL2CAPSocket` for unit testing GATT Client and Server

- Sources/BluetoothUUID.swift
- Sources/CompanyIdentifier.swift
- Sources/HCICommandTimeout.swift
- Sources/iBeacon.swift
- Tests/BluetoothTests/AttributeProtocolTests.swift
- Tests/BluetoothTests/BluetoothTests.swift
- Tests/BluetoothTests/BluetoothUUIDTests.swift
- Tests/BluetoothTests/HCITests.swift
- Tests/BluetoothTests/iBeaconTests.swift
**Issue**
WIP for #23 and #27.
Adds unit tests for `iBeacon`, ATT PDUs, `CompanyIdentifier` and other types.
`iBeacon.swift`
`iBeaconTests.swift`
> Updated unit tests

- Sources/LowEnergyResolvingList.swift
**Issue**
Fixes #40.
Remove extra parameter on the method `lowEnergyRemoveDeviceFromResolvingList ()`.
LowEnergyResolvingList.swift
> Fixed `lowEnergyRemoveDeviceFromResolvingList ()` method

- Sources/GATTCharacteristic.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
**Issue**
#58 .
added aerobic heart rate upper limit
GATTCharacteristic.swift
> Added GATT Aerobic Heart Rate Upper Limit Characteristic

- Sources/GATTCharacteristic.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
**Issue**
#58.
added alert level characteistic.
GATTCharacteristics.swift
> Added GATT Alert Level Characteristic

- Sources/GATTCharacteristic.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
**Issue**
#58 .
Added GATTAerobicThreshold.
GATTCharacteristics.swift
> Added Aerobic Threshold

- Sources/GATTCharacteristic.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
**Issue**
Fixes #58.
Added GATT Characteristic Analog
GATTCharacteristic.swift
> Added GATT Analog

- Sources/GATTAltitude.swift
- Sources/GATTCharacteristic.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
- Xcode/Bluetooth.xcodeproj/project.pbxproj
**Issue**
Fixes #58.
added GATT Characteristic Altitude
GATTCharacteristic.swift
> Added GATT Altitude Characteristic

- Sources/GATTCentralAddressResolution.swift
- Sources/Integer.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
- Xcode/Bluetooth.xcodeproj/project.pbxproj
**Issue**
#58
Added GATT Central Address Resolution Characteristic
`GATTCentralAddressResolution.swift`
> Added GATT Central Address Resolution Characteristic

- Sources/GATTFirmwareRevisionString.swift
- Sources/GATTManufacturerNameString.swift
- Sources/GATTModelNumber.swift
- Sources/GATTPnPID.swift
- Sources/GATTSoftwareRevisionString.swift
- Sources/GATTSystemID.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
- Xcode/Bluetooth.xcodeproj/project.pbxproj
**Issue**
#58
Description of the changes in this pull request.
Added GATTFirmwareRevisionString, GATTSoftwareRevisionString, GATTModelNumberString and GATTManufacturerNameString
GATTModelNumberString.swift
GATTFirmwareRevisionString.swift
GATTSoftwareRevisionString.swift
GATTManufacturerNameString.swift
> Added GATT Device Information Characteristics

- Sources/CGMSessionRunTime.swift
- Sources/GATTCGMSessionRunTime.swift
- Sources/GATTCharacteristic.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
- Xcode/Bluetooth.xcodeproj/project.pbxproj
**Issue**
#58
Added GATT CGM Session Run Time Characteristic
`GATTCharacteristicTests.swift`
> Added GATT CGM Session Run Time Characteristic

- Sources/GATTHardwareRevisionString.swift
- Sources/GATTSerialNumberString.swift
- Sources/GATTSystemID.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
- Xcode/Bluetooth.xcodeproj/project.pbxproj
**Issue**
#58.
Added GATT Hardware Revision String and Serial Number Characteristics
GATTHardwareRevisionString.swift and GATTSerialNumberString.swift
> Added GATT Hardware Revision String and Serial Number Characteristics

- Sources/GATTIndoorPositioningConfiguration.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
- Xcode/Bluetooth.xcodeproj/project.pbxproj
**Issue**
#58
Added GATT Indoor Positioning Configuration Characteristic
`GATTIndoorPositioningConfiguration.swift`
> Added GATT Indoor Positioning Configuration Characteristic

- Sources/GATTFloorNumber.swift
- Sources/GATTLatitude.swift
- Sources/GATTLocalEastCoordinate.swift
- Sources/GATTLocalNorthCoordinate.swift
- Sources/GATTLocationName.swift
- Sources/GATTLongitude.swift
- Sources/GATTUncertainty.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
- Xcode/Bluetooth.xcodeproj/project.pbxproj
**Issue**
#58
Added GATTLongitude, GATTLatitude and GATTLocalNorthCoordinate
GATTLongitud.swift, GATTLatitude.swift, GATTLocalNorthCoordinate.swift
> Add GATT Characteristics for Indoor Positioning Service

- Sources/GATTScanIntervalWindow.swift
- Sources/GATTScanRefresh.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
- Xcode/Bluetooth.xcodeproj/project.pbxproj
**Issue**
#58.
Added GATT Scan Characteristics.
GATTScanRefresh.swift, GATTScanIntervalWindow.swift
> Added GATT Scan Characteristics

- Sources/GATTObjectID.swift
- Sources/GATTObjectName.swift
- Sources/GATTObjectSize.swift
- Sources/GATTObjectType.swift
- Sources/UInt24.swift
- Sources/UInt48.swift
- Tests/BluetoothTests/GATTCharacteristicTests.swift
- Tests/BluetoothTests/GATTTests.swift
- Tests/BluetoothTests/L2CAPSocket.swift
- Tests/BluetoothTests/UInt24Tests.swift
- Tests/BluetoothTests/UInt48Tests.swift
- Xcode/Bluetooth.xcodeproj/project.pbxproj
**Issue**
#58
Added GATT Object Characteristics
GATTObjectType.swift, GATTObjectName.swift, GATTObjectSize.swift, GATTObjectId.swift, UInt48.swift
> Added GATT Object Characteristics

- Sources/ATTConnection.swift
- Sources/ATTHandleValueConfirmation.swift
- Sources/ATTHandleValueIndication.swift
- Sources/GATTClient.swift
- Sources/GATTServer.swift
- Tests/BluetoothTests/GATTTests.swift
- Tests/BluetoothTests/L2CAPSocket.swift
- Tests/BluetoothTests/TestProfile.swift
**Issue**
Fixes #32 .
Implements GATT Indications for `GATTClient` and `GATTServer`.
`GATTClient.swift`
> Implemented GATT Indications

- Sources/Bluetooth/BluetoothUUID.swift
- Sources/Bluetooth/Extensions/Data.swift
- Sources/Bluetooth/Extensions/DataConvertible.swift
- Sources/Bluetooth/Extensions/Hexadecimal.swift
- Sources/Bluetooth/LowEnergyAdvertisingData.swift
- Sources/Bluetooth/iBeacon.swift
- Sources/BluetoothGAP/GAPData.swift
- Sources/BluetoothGAP/GAPDataEncoder.swift
- Sources/BluetoothGAP/GAPDataType.swift
- Sources/BluetoothGAP/GAPFlags.swift
- Sources/BluetoothGAP/GAPLEDeviceAddress.swift
- Sources/BluetoothGAP/GAPManufacturerSpecificData.swift
- Sources/BluetoothGAP/GAPSimplePairingHashC.swift
- Sources/BluetoothGAP/iBeacon.swift
- Tests/BluetoothTests/GAPTests.swift
- Tests/BluetoothTests/iBeaconTests.swift
Optimized `GAPManufacturerData` internal storage.
`GAPManufacturerData.swift`
> Optimized storage for `GAPManufacturerSpecificData`

- Sources/Bluetooth/L2CAPSocket.swift
- Sources/BluetoothGATT/ATTConnection.swift
- Sources/BluetoothGATT/GATTClient.swift
- Sources/BluetoothHCI/BluetoothHostController.swift
- Sources/BluetoothHCI/HCILESetScanEnable.swift
- Tests/BluetoothTests/GATTTests.swift
- Tests/BluetoothTests/L2CAPSocket.swift
“Receive" was spelled incorrectly throughout this whole project, just make sure it compiles
> Fix the spelling of receive

- Sources/Bluetooth/Extensions/UUID.swift
- Sources/Bluetooth/UInt128.swift
- Sources/Bluetooth/iBeacon.swift
- Sources/BluetoothGAP/Extensions/UUID.swift
- Tests/BluetoothTests/UUIDTests.swift
**Issue**
Fixes #157 .
Adds `UUID` type when Foundation is missing, along with unit tests.
`UUID.swift`
> Add `UUID` implementation

- .github/workflows/swift-arm.yml
- .gitignore
- Package.swift
- Sources/Bluetooth/Address.swift
- Sources/Bluetooth/BluetoothUUID.swift
- Sources/BluetoothMacros/BluetoothAddress.swift
- Sources/BluetoothMacros/BluetoothUUID.swift
- Sources/BluetoothMacros/Extensions/Hexadecimal.swift
- Sources/BluetoothMacros/Plugins.swift
- Tests/BluetoothTests/AddressTests.swift
- Tests/BluetoothTests/BluetoothUUIDTests.swift
**Issue**
Fixes #171 
Adds macros for `BluetoothAddress` and `BluetoothUUID` for string validation at compile time.
`Sources/BluetoothMacros/Plugins.swift`
> Add macros

- .github/workflows/swift-arm.yml
- .github/workflows/swift.yml
> Update GitHub CI

- .github/workflows/swift-arm.yml
- .github/workflows/swift.yml
- Package.swift
> Update for Swift 6.1
